apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce
    tier: backend
  name: product-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      tier: backend
  template:
    metadata:
      labels:
        app: ecommerce
        tier: backend
    spec:
      containers:
        - image: dirol13/kbtu-sa-task3:v4
          imagePullPolicy: "IfNotPresent"
          name: product-be
          ports:
            - containerPort: 8080
      restartPolicy: Always
