apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task2-ingress
  namespace: task2
spec:
  rules:
    - host: sa.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 8080
    - host: api.sa.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000
